language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - python setup.py install
  - pip install bottle

before_script:
  - python test_server.py
  - sleep 5

script: py.test run_tests.py
