language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - python setup.py install
  - pip install bottle

before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/pyapitest_bottle.pid --make-pidfile --background --exec test_server.py"
  - sleep 5

script: py.test run_tests.py
